# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [41]:
import numpy as np
a=np.random.randint(10,size=5)
print(a)
print('list(a): ', list(a))
print('tolist(a): ', a.tolist())

b=np.random.randint(10,size=6).reshape(3,2)
print(b)
print('list(a): ', list(b))
print('tolist: ', b.tolist())

#Ans:tolist可以將二維巢狀的array皆轉為巢狀的list

[4 9 2 6 5]
list(a):  [4, 9, 2, 6, 5]
tolist(a):  [4, 9, 2, 6, 5]
[[1 7]
 [5 4]
 [2 5]]
list(a):  [array([1, 7]), array([5, 4]), array([2, 5])]
tolist:  [[1, 7], [5, 4], [2, 5]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [42]:
# 記得先 Import 正確的套件

import numpy as np
a=np.random.randint(10, size=6).reshape(3,2)
print(a)
print('ndim(a): ', a.ndim)
print('shape(a): ', a.shape)
print('size(a): ', a.size)
print('dtype(a): ',a.dtype)
print('itemsize(a): ', a.itemsize)
print('length(a): ', len(a))
print('type(a): ',type(a))

[[9 3]
 [0 6]
 [1 4]]
ndim(a):  2
shape(a):  (3, 2)
size(a):  6
dtype(a):  int32
itemsize(a):  4
length(a):  3
type(a):  <class 'numpy.ndarray'>


In [28]:

a = np.random.randint(10, size=6)
print(a)
print('ndim(a): ', a.ndim)
print('shape(a): ', a.shape)
print('size(a): ', a.size)
print('dtype(a): ',a.dtype)
print('itemsize(a): ', a.itemsize)
print('length(a): ', len(a))
print('type(a): ',type(a))

[1 8 4 9 9 8]
ndim(a):  1
shape(a):  (6,)
size(a):  6
dtype(a):  int32
itemsize(a):  4
length(a):  6
type(a):  <class 'numpy.ndarray'>


In [26]:
b = np.random.randint(10, size=(3,4)) 
print(b)
print('ndim(a): ', b.ndim)
print('shape(a): ', b.shape)
print('size(a): ', b.size)
print('dtype(a): ',b.dtype)
print('itemsize(a): ', b.itemsize)
print('length(a): ', len(b))
print('type(a): ',type(b))

[[0 0 5 9]
 [1 2 4 6]
 [9 1 6 1]]
ndim(a):  2
shape(a):  (3, 4)
size(a):  12
dtype(a):  int32
itemsize(a):  4
length(a):  3
type(a):  <class 'numpy.ndarray'>


In [27]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print('ndim(a): ', c.ndim)
print('shape(a): ', c.shape)
print('size(a): ', c.size)
print('dtype(a): ',c.dtype)
print('itemsize(a): ', c.itemsize)
print('length(a): ', len(c))
print('type(a): ',type(c))

[[[7 6]
  [0 4]
  [8 7]]

 [[0 0]
  [7 8]
  [2 0]]]
ndim(a):  3
shape(a):  (2, 3, 2)
size(a):  12
dtype(a):  int32
itemsize(a):  4
length(a):  2
type(a):  <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [38]:
a = np.random.randint(10, size=6) 
print(a)
print(a.tolist())
print(list(a))


[2 0 3 8 2 4]
[2, 0, 3, 8, 2, 4]
[2, 0, 3, 8, 2, 4]


In [39]:
b = np.random.randint(10, size=(3,4)) 

print(b)
print(b.tolist())
print(list(b))


[[0 7 3 4]
 [0 6 1 6]
 [8 8 3 3]]
[[0, 7, 3, 4], [0, 6, 1, 6], [8, 8, 3, 3]]
[array([0, 7, 3, 4]), array([0, 6, 1, 6]), array([8, 8, 3, 3])]


In [40]:
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.tolist())
print(list(c))


[[[1 2]
  [0 5]
  [6 1]]

 [[6 6]
  [4 4]
  [1 0]]]
[[[1, 2], [0, 5], [6, 1]], [[6, 6], [4, 4], [1, 0]]]
[array([[1, 2],
       [0, 5],
       [6, 1]]), array([[6, 6],
       [4, 4],
       [1, 0]])]


In [34]:
def tolist(iterable):
    if type(iterable)!=np.ndarray:
        return iterable
    newlist=[]
    for obj in iterable:
        newlist.append(tolist(obj))
    return list(newlist)

print(tolist(a))
print(tolist(b))
print(tolist(c))

[5, 5, 3, 9, 1, 1]
[[1, 8, 0, 7], [5, 9, 1, 1], [2, 2, 5, 8]]
[[[8, 0], [3, 0], [6, 6]], [[7, 9], [3, 0], [0, 8]]]


In [36]:
def tolist(iterable):
    if type(iterable)!=np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]
print(tolist(a))
print(tolist(b))
print(tolist(c))

[5, 5, 3, 9, 1, 1]
[[1, 8, 0, 7], [5, 9, 1, 1], [2, 2, 5, 8]]
[[[8, 0], [3, 0], [6, 6]], [[7, 9], [3, 0], [0, 8]]]


In [37]:
print(tolist(a))
print(tolist(b))
print(tolist(c))

[5, 5, 3, 9, 1, 1]
[[1, 8, 0, 7], [5, 9, 1, 1], [2, 2, 5, 8]]
[[[8, 0], [3, 0], [6, 6]], [[7, 9], [3, 0], [0, 8]]]
