# [作業目標]

1. 請比較對一個 100 x 100 * 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。

2. 如何從一個陣列中，找出出現頻率最高的數值與位置？

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. 請比較對一個 1000 x 100 x 100 的陣列，使用不同方法對每一個元素 +1 的時間比較。




In [5]:
# 記得先 Import 正確的套件
import numpy as np

In [18]:
Z = np.random.randint(0, 10, 1000000).reshape(100, 100, 100)
print(Z)

[[[0 2 7 ... 1 0 5]
  [3 4 8 ... 7 2 9]
  [5 7 9 ... 1 8 2]
  ...
  [0 4 5 ... 8 8 5]
  [2 2 8 ... 0 1 4]
  [2 2 5 ... 1 6 0]]

 [[4 3 2 ... 4 8 6]
  [4 4 7 ... 1 5 1]
  [4 1 5 ... 0 7 6]
  ...
  [8 9 4 ... 1 6 4]
  [0 3 8 ... 5 7 3]
  [5 5 7 ... 0 3 9]]

 [[9 9 6 ... 8 1 4]
  [8 5 6 ... 5 6 9]
  [1 8 6 ... 7 1 4]
  ...
  [5 1 2 ... 5 2 4]
  [0 0 8 ... 7 8 8]
  [6 0 5 ... 9 4 5]]

 ...

 [[2 9 7 ... 8 0 7]
  [6 2 4 ... 5 0 9]
  [6 2 7 ... 5 8 1]
  ...
  [8 8 2 ... 6 8 7]
  [7 2 4 ... 7 5 2]
  [5 2 4 ... 3 7 1]]

 [[0 1 9 ... 4 5 7]
  [1 0 5 ... 1 8 3]
  [9 8 7 ... 6 8 8]
  ...
  [1 3 4 ... 5 5 5]
  [3 1 2 ... 4 3 1]
  [3 5 1 ... 1 2 7]]

 [[3 2 6 ... 9 2 8]
  [7 8 8 ... 5 0 4]
  [4 0 3 ... 0 1 7]
  ...
  [6 0 0 ... 7 6 6]
  [3 0 0 ... 8 4 7]
  [2 9 8 ... 0 8 4]]]


In [19]:
%timeit -n 10 a = 2

for i in Z:
    for j in i:
        for k in j:
            i=i+1

31.4 ns ± 17.3 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [20]:
%timeit -n 10 a = 2

for i in Z.flat:
    i=i+1

20 ns ± 9.26 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
%timeit -n 10 a = 2

for i in np.nditer(Z):
    i=i+1

32.9 ns ± 15.8 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
%timeit -n 10 a = 2

Z=Z+1

34.3 ns ± 15.9 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 2. 如何從一個陣列中，找出出現頻率最高的數值與位置？


In [38]:

Z = np.random.randint(0,10,50)
print(Z)


[1 1 5 0 2 7 5 1 4 1 1 5 0 2 5 6 7 8 8 1 8 6 6 8 9 6 1 4 8 0 2 6 0 0 4 2 8
 4 2 9 8 1 6 8 9 8 5 8 0 4]


In [45]:
count=np.bincount(Z)
print(count)
count_position=count.argmax()
print('出現頻率最高的數字:',count_position)
print('出現頻率最高數字的位置',np.where(Z==count.argmax()))


[ 6  8  5  0  5  5  6  2 10  3]
出現頻率最高的數字: 8
出現頻率最高數字的位置 (array([17, 18, 20, 23, 28, 36, 40, 43, 45, 47], dtype=int64),)


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [46]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[0, 7, 9, 3, 3, 0]
[0, 7, 9, 3, 3, 0]
[[0, 9, 7, 3], [1, 2, 5, 0], [3, 2, 0, 7]]
[array([0, 9, 7, 3]), array([1, 2, 5, 0]), array([3, 2, 0, 7])]
[[[8, 6], [3, 4], [3, 8]], [[6, 0], [5, 6], [1, 9]]]
[array([[8, 6],
       [3, 4],
       [3, 8]]), array([[6, 0],
       [5, 6],
       [1, 9]])]


In [47]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    return [tolist(obj) for obj in iterable]

print(tolist(a))
print(tolist(b))
print(tolist(c))

[0, 7, 9, 3, 3, 0]
[[0, 9, 7, 3], [1, 2, 5, 0], [3, 2, 0, 7]]
[[[8, 6], [3, 4], [3, 8]], [[6, 0], [5, 6], [1, 9]]]
