# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [24]:
import numpy as np
print(np.zeros((2,3)))#會產生真正的0
print(np.empty((2,3)))#會產生一個近似於0的陣列，empty可以使用於快速的初始化，但之後就會數值複寫，速度較zero快

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [25]:
import numpy as np
a = np.random.rand(2, 3)
print(a)
a=a*100

[[0.99915052 0.49425693 0.36277383]
 [0.2804207  0.56847984 0.65227654]]


In [26]:
print(a.round())
print(np.round(a))

[[100.  49.  36.]
 [ 28.  57.  65.]]
[[100.  49.  36.]
 [ 28.  57.  65.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [31]:
m = 20
n = 40

a=np.random.rand(2,3)*(n-m)
b=a
print(a)
print(b%1) #只取小數點後第一位以後的數字
print(a-b%1+m)


[[ 8.08482415  8.52765251 16.08570052]
 [ 2.15040933  4.56300623 13.90139536]]
[[0.08482415 0.52765251 0.08570052]
 [0.15040933 0.56300623 0.90139536]]
[[28. 28. 36.]
 [22. 24. 33.]]
