In [1]:
#載入Numpy套件
import numpy as np

#檢查版本
print(np)
print(np.__version__)

<module 'numpy' from 'C:\\Users\\chich\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.20.3


In [7]:
#從一個陣列開始
a=np.arange(15).reshape(3,5)

#利用print印出陣列
print(a)

#利用Jupyter印出陣列
a

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
#陣列的常用屬性

print('ndim: ',a.ndim)
print('shape: ',a.shape)
print('size: ',a.size)
print('dtype: ',a.dtype)
print('itemsize: ',a.itemsize)
print('data: ',a.data)

ndim:  2
shape:  (3, 5)
size:  15
dtype:  int32
itemsize:  4
data:  <memory at 0x0000021A1C36E450>


In [18]:
#list和array的轉換
print('list(a): ',list(a))
print('tolist(a): ',a.tolist())

list(a):  [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
tolist(a):  [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
